version: '3'
services:
  python:
    image: python:3.9
    volumes:
      - ./app:/app
    working_dir: /app
    command: python app.py
    ports:
      - 5000:5000

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
